import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export const TYR_VERSION = "0.30.0";
export const LATCHFLO_VERSION = "0.15.0";
export const ASYNC_BULKHEAD_LLM_VERSION = "3.17.0";
export const ASYNC_BULKHEAD_TS_VERSION = "1.0.1";
export const OLLAMA_VERSION = "0.12.3";
export const DEFAULT_TYR_IMAGE = `tyr-admission-controller:${TYR_VERSION}`;
export const DEFAULT_LATCHFLO_IMAGE = `latchflo-control-plane:${LATCHFLO_VERSION}`;
export const DEFAULT_OLLAMA_IMAGE = `ollama/ollama:${OLLAMA_VERSION}`;

/**
 * Default weights for the local inference benchmark.
 *
 * Deliberately the smallest model that still streams coherent text: the
 * benchmark measures admission control in front of a saturated server, not the
 * model, and a laptop or a CI runner has to be able to pull and hold it. Bigger
 * weights are a `--model` away and change nothing about what is measured.
 */
export const DEFAULT_LOCAL_MODEL = "qwen3:0.6b";

function token(prefix) {
  return `${prefix}-${randomBytes(32).toString("base64url")}`;
}

export function imageMatchesVersion(image, version) {
  return typeof image === "string" && new RegExp(`:${version.replaceAll(".", "\\.")}$`).test(image.trim());
}

function migrateDefaultImage(text, key, repository, expectedImage) {
  const pattern = new RegExp(`^${key}=([^\r\n]+)$`, "m");
  const match = pattern.exec(text);
  if (!match) return { text, changed: false };
  const configured = match[1].trim();
  const localDefault = new RegExp(`^${repository}:\\d+\\.\\d+\\.\\d+$`);
  if (!localDefault.test(configured) || configured === expectedImage) {
    return { text, changed: false };
  }
  return { text: text.replace(pattern, `${key}=${expectedImage}`), changed: true };
}

/**
 * Adds `key=value` after `anchor` when the file has no such key at all.
 *
 * A `.env` generated by an older release predates keys a newer one needs. It
 * must gain them, because the alternative is a demo that fails at the compose
 * step with an unset-variable error naming a variable the operator never chose
 * not to set. An existing value is never touched: only absence is migrated.
 */
function ensureEnvLine(text, key, value, anchor) {
  if (new RegExp(`^${key}=`, "m").test(text)) return { text, changed: false };
  const line = `${key}=${value}`;
  return {
    text: anchor.test(text)
      ? text.replace(anchor, (matched) => `${matched}\n${line}`)
      : `${text.replace(/\s*$/, "")}\n${line}\n`,
    changed: true,
  };
}

function migrateExistingEnv(file, { quiet }) {
  let text = readFileSync(file, "utf8");
  let changed = false;
  for (const [key, repository, expectedImage] of [
    ["MOFLUX_TYR_IMAGE", "tyr-admission-controller", DEFAULT_TYR_IMAGE],
    ["MOFLUX_LATCHFLO_IMAGE", "latchflo-control-plane", DEFAULT_LATCHFLO_IMAGE],
    ["MOFLUX_OLLAMA_IMAGE", "ollama/ollama", DEFAULT_OLLAMA_IMAGE],
  ]) {
    const migrated = migrateDefaultImage(text, key, repository, expectedImage);
    text = migrated.text;
    changed ||= migrated.changed;
  }
  const compatibility = `# Runtime compatibility: Tyr ${TYR_VERSION}, Latchflo ${LATCHFLO_VERSION}.`;
  const updatedText = text.replace(
    /^# Runtime compatibility: Tyr [^,]+, Latchflo [^.]+\.[^.]+\.[^.]+\.$/m,
    compatibility,
  );
  changed ||= updatedText !== text;
  text = updatedText;

  for (const [key, value] of [
    ["MOFLUX_OLLAMA_IMAGE", DEFAULT_OLLAMA_IMAGE],
    ["MOFLUX_LOCAL_MODEL", DEFAULT_LOCAL_MODEL],
  ]) {
    const ensured = ensureEnvLine(text, key, value, /^MOFLUX_LATCHFLO_IMAGE=[^\r\n]+$/m);
    text = ensured.text;
    changed ||= ensured.changed;
  }

  if (!/^TYR_ROUTING_SECRET=/m.test(text)) {
    const routingSecret = process.env.TYR_ROUTING_SECRET || token("moflux-demo-routing");
    const line = `TYR_ROUTING_SECRET=${routingSecret}`;
    const bootstrapLine = /^LATCHFLO_AGENT_BOOTSTRAP_TOKEN=[^\r\n]+$/m;
    text = bootstrapLine.test(text)
      ? text.replace(bootstrapLine, (value) => `${value}\n${line}`)
      : `${text.replace(/\s*$/, "")}\n${line}\n`;
    changed = true;
  }
  if (changed) {
    writeFileSync(file, text, { mode: 0o600 });
    try { chmodSync(file, 0o600); } catch { /* best effort on non-POSIX filesystems */ }
    if (!quiet) console.log(`Updated local default image tags in ${path.relative(process.cwd(), file)}.`);
  }
  return { created: false, updated: changed, file };
}

export function ensureDemoEnv(file, { quiet = false } = {}) {
  if (existsSync(file)) return migrateExistingEnv(file, { quiet });

  const values = {
    MOFLUX_TYR_IMAGE: process.env.MOFLUX_TYR_IMAGE || DEFAULT_TYR_IMAGE,
    MOFLUX_LATCHFLO_IMAGE: process.env.MOFLUX_LATCHFLO_IMAGE || DEFAULT_LATCHFLO_IMAGE,
    MOFLUX_OLLAMA_IMAGE: process.env.MOFLUX_OLLAMA_IMAGE || DEFAULT_OLLAMA_IMAGE,
    MOFLUX_LOCAL_MODEL: process.env.MOFLUX_LOCAL_MODEL || DEFAULT_LOCAL_MODEL,
    LATCHFLO_ADMIN_TOKEN: process.env.LATCHFLO_ADMIN_TOKEN || token("moflux-demo-admin"),
    LATCHFLO_AGENT_BOOTSTRAP_TOKEN:
      process.env.LATCHFLO_AGENT_BOOTSTRAP_TOKEN || token("moflux-demo-bootstrap"),
    TYR_ROUTING_SECRET: process.env.TYR_ROUTING_SECRET || token("moflux-demo-routing"),
    MOFLUX_TYR_USER: process.env.MOFLUX_TYR_USER || "0:0",
  };

  mkdirSync(path.dirname(file), { recursive: true });
  const body = [
    "# Generated by moflux-bench. This file is local-only and ignored by Git.",
    `# Runtime compatibility: Tyr ${TYR_VERSION}, Latchflo ${LATCHFLO_VERSION}.`,
    `MOFLUX_TYR_IMAGE=${values.MOFLUX_TYR_IMAGE}`,
    `MOFLUX_LATCHFLO_IMAGE=${values.MOFLUX_LATCHFLO_IMAGE}`,
    `MOFLUX_OLLAMA_IMAGE=${values.MOFLUX_OLLAMA_IMAGE}`,
    `MOFLUX_LOCAL_MODEL=${values.MOFLUX_LOCAL_MODEL}`,
    `LATCHFLO_ADMIN_TOKEN=${values.LATCHFLO_ADMIN_TOKEN}`,
    `LATCHFLO_AGENT_BOOTSTRAP_TOKEN=${values.LATCHFLO_AGENT_BOOTSTRAP_TOKEN}`,
    `TYR_ROUTING_SECRET=${values.TYR_ROUTING_SECRET}`,
    `MOFLUX_TYR_USER=${values.MOFLUX_TYR_USER}`,
    "",
  ].join("\n");
  writeFileSync(file, body, { mode: 0o600 });
  try { chmodSync(file, 0o600); } catch { /* best effort on non-POSIX filesystems */ }
  if (!quiet) {
    console.log(`Created ${path.relative(process.cwd(), file)} for Tyr ${TYR_VERSION} + Latchflo ${LATCHFLO_VERSION}.`);
  }
  return { created: true, file, values };
}
