#!/usr/bin/env node
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import {
  DEFAULT_LATCHFLO_IMAGE,
  DEFAULT_LOCAL_MODEL,
  DEFAULT_OLLAMA_IMAGE,
  DEFAULT_TYR_IMAGE,
  DEFAULT_VLLM_IMAGE,
  DEFAULT_VLLM_MODEL,
  DEFAULT_VLLM_MODEL_REVISION,
  DEFAULT_VLLM_SERVED_MODEL,
  LATCHFLO_VERSION,
  OLLAMA_VERSION,
  TYR_VERSION,
  VLLM_VERSION,
  ensureDemoEnv,
  imageMatchesVersion,
} from "./env-lib.mjs";

const temp = mkdtempSync(path.join(tmpdir(), "moflux-env-"));
const file = path.join(temp, ".env");
try {
  const first = ensureDemoEnv(file, { quiet: true });
  assert.equal(first.created, true);
  const text = readFileSync(file, "utf8");
  assert.match(text, new RegExp(`^MOFLUX_TYR_IMAGE=${DEFAULT_TYR_IMAGE}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_LATCHFLO_IMAGE=${DEFAULT_LATCHFLO_IMAGE}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_OLLAMA_IMAGE=${DEFAULT_OLLAMA_IMAGE}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_LOCAL_MODEL=${DEFAULT_LOCAL_MODEL}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_VLLM_IMAGE=${DEFAULT_VLLM_IMAGE}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_VLLM_MODEL=${DEFAULT_VLLM_MODEL}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_VLLM_SERVED_MODEL=${DEFAULT_VLLM_SERVED_MODEL}$`, "m"));
  assert.match(text, new RegExp(`^MOFLUX_VLLM_MODEL_REVISION=${DEFAULT_VLLM_MODEL_REVISION}$`, "m"));
  assert.match(text, /^LATCHFLO_ADMIN_TOKEN=moflux-demo-admin-[A-Za-z0-9_-]{40,}$/m);
  assert.match(text, /^LATCHFLO_AGENT_BOOTSTRAP_TOKEN=moflux-demo-bootstrap-[A-Za-z0-9_-]{40,}$/m);
  assert.match(text, /^TYR_ROUTING_SECRET=moflux-demo-routing-[A-Za-z0-9_-]{40,}$/m);
  if (process.platform !== "win32") assert.equal(statSync(file).mode & 0o777, 0o600);
  assert.equal(imageMatchesVersion(DEFAULT_TYR_IMAGE, TYR_VERSION), true);
  assert.equal(imageMatchesVersion(DEFAULT_LATCHFLO_IMAGE, LATCHFLO_VERSION), true);
  assert.equal(imageMatchesVersion(DEFAULT_OLLAMA_IMAGE, OLLAMA_VERSION), true);
  assert.equal(imageMatchesVersion(DEFAULT_VLLM_IMAGE, VLLM_VERSION), true);
  assert.equal(imageMatchesVersion("tyr-admission-controller:0.15.1", TYR_VERSION), false);

  writeFileSync(
    file,
    [
      "# Generated by moflux-bench. This file is local-only and ignored by Git.",
      "# Runtime compatibility: Tyr 0.15.1, Latchflo 0.4.2.",
      "MOFLUX_TYR_IMAGE=tyr-admission-controller:0.15.1",
      "MOFLUX_LATCHFLO_IMAGE=latchflo-control-plane:0.4.2",
      "LATCHFLO_ADMIN_TOKEN=preserve-admin",
      "LATCHFLO_AGENT_BOOTSTRAP_TOKEN=preserve-bootstrap",
      "MOFLUX_TYR_USER=0:0",
      "",
    ].join("\n"),
  );
  const migrated = ensureDemoEnv(file, { quiet: true });
  assert.equal(migrated.created, false);
  assert.equal(migrated.updated, true);
  const migratedText = readFileSync(file, "utf8");
  assert.match(migratedText, new RegExp(`^MOFLUX_TYR_IMAGE=${DEFAULT_TYR_IMAGE}$`, "m"));
  assert.match(migratedText, new RegExp(`^MOFLUX_LATCHFLO_IMAGE=${DEFAULT_LATCHFLO_IMAGE}$`, "m"));
  assert.match(migratedText, /^LATCHFLO_ADMIN_TOKEN=preserve-admin$/m);
  // A .env written before the local inference benchmark existed has neither
  // key. It must gain both, or demo:local fails at compose with an
  // unset-variable error naming a variable the operator never chose to omit.
  assert.match(migratedText, new RegExp(`^MOFLUX_OLLAMA_IMAGE=${DEFAULT_OLLAMA_IMAGE}$`, "m"));
  assert.match(migratedText, new RegExp(`^MOFLUX_LOCAL_MODEL=${DEFAULT_LOCAL_MODEL}$`, "m"));
  assert.match(migratedText, new RegExp(`^MOFLUX_VLLM_IMAGE=${DEFAULT_VLLM_IMAGE}$`, "m"));
  assert.match(migratedText, new RegExp(`^MOFLUX_VLLM_MODEL=${DEFAULT_VLLM_MODEL}$`, "m"));
  assert.match(migratedText, new RegExp(`^MOFLUX_VLLM_SERVED_MODEL=${DEFAULT_VLLM_SERVED_MODEL}$`, "m"));
  assert.match(migratedText, new RegExp(`^MOFLUX_VLLM_MODEL_REVISION=${DEFAULT_VLLM_MODEL_REVISION}$`, "m"));
  assert.match(migratedText, /^LATCHFLO_AGENT_BOOTSTRAP_TOKEN=preserve-bootstrap$/m);
  assert.match(migratedText, /^TYR_ROUTING_SECRET=moflux-demo-routing-[A-Za-z0-9_-]{40,}$/m);

  writeFileSync(file, [
    "# Runtime compatibility: Tyr 0.31.0, Latchflo 0.18.0.",
    "MOFLUX_TYR_IMAGE=tyr-admission-controller:0.31.0",
    "MOFLUX_LATCHFLO_IMAGE=latchflo-control-plane:0.18.0",
    "LATCHFLO_ADMIN_TOKEN=preserve-admin",
    "LATCHFLO_AGENT_BOOTSTRAP_TOKEN=preserve-bootstrap",
    "TYR_ROUTING_SECRET=preserve-routing-secret-at-least-32-characters",
    "",
  ].join("\n"));
  assert.equal(ensureDemoEnv(file, { quiet: true }).updated, true);
  const upgraded = readFileSync(file, "utf8");
  assert.match(upgraded, /^MOFLUX_TYR_IMAGE=tyr-admission-controller:0\.33\.0$/m);
  assert.match(upgraded, /^MOFLUX_LATCHFLO_IMAGE=latchflo-control-plane:0\.19\.0$/m);
  assert.match(upgraded, /^# Runtime compatibility: Tyr 0\.33\.0, Latchflo 0\.19\.0\.$/m);
  assert.match(upgraded, /^LATCHFLO_ADMIN_TOKEN=preserve-admin$/m);
  assert.match(upgraded, /^LATCHFLO_AGENT_BOOTSTRAP_TOKEN=preserve-bootstrap$/m);
  assert.match(upgraded, /^TYR_ROUTING_SECRET=preserve-routing-secret-at-least-32-characters$/m);
  assert.equal(ensureDemoEnv(file, { quiet: true }).updated, false);

  writeFileSync(
    file,
    [
      "MOFLUX_TYR_IMAGE=registry.example/tyr@sha256:abc",
      "MOFLUX_LATCHFLO_IMAGE=registry.example/latchflo@sha256:def",
      "MOFLUX_OLLAMA_IMAGE=registry.example/ollama@sha256:aaa",
      "MOFLUX_LOCAL_MODEL=llama3.2:1b",
      "MOFLUX_VLLM_IMAGE=registry.example/vllm@sha256:bbb",
      "MOFLUX_VLLM_MODEL=Example/Model",
      "MOFLUX_VLLM_SERVED_MODEL=moflux-vllm",
      "MOFLUX_VLLM_MODEL_REVISION=0123456789012345678901234567890123456789",
      "LATCHFLO_ADMIN_TOKEN=custom-admin",
      "LATCHFLO_AGENT_BOOTSTRAP_TOKEN=custom-bootstrap",
      "TYR_ROUTING_SECRET=custom-routing-secret-with-at-least-32-chars",
      "",
    ].join("\n"),
  );
  const custom = ensureDemoEnv(file, { quiet: true });
  assert.equal(custom.updated, false);
  const customText = readFileSync(file, "utf8");
  assert.match(customText, /registry\.example\/latchflo@sha256:def/);
  // A deliberately chosen registry path and model survive the migration: only
  // an unset key is filled in, never an operator's answer.
  assert.match(customText, /^MOFLUX_OLLAMA_IMAGE=registry\.example\/ollama@sha256:aaa$/m);
  assert.match(customText, /^MOFLUX_LOCAL_MODEL=llama3\.2:1b$/m);
  console.log("PASS  demo environment is generated safely, migrates local runtime and inference defaults, and provisions routing credentials");
} finally {
  rmSync(temp, { recursive: true, force: true });
}
